### ISSUE TITLE
*Setup OTP deployment environments

### ISSUE THREAD

**Issue by SKairinos** [ocadotechnology/codeforlife-workspace#173]
- [ ] https://github.com/ocadotechnology/codeforlife-workspace/issues/141
- [ ] https://github.com/ocadotechnology/codeforlife-workspace/issues/140
- [x] https://github.com/ocadotechnology/codeforlife-workspace/issues/139
- [x] https://github.com/ocadotechnology/codeforlife-workspace/issues/137
- [ ] https://github.com/ocadotechnology/codeforlife-workspace/issues/136
- [ ] https://github.com/ocadotechnology/codeforlife-workspace/issues/135
- [ ] https://github.com/ocadotechnology/codeforlife-workspace/issues/134
- [ ] ocadotechnology/rapid-router#1761
