### ISSUE TITLE
Branding for Python hub

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-workspace#517]
**Summary**
We would like to create a look and feel for the new Python Hub. 
We want something that attracts kids from around aged 11 years old. So think teens.

**User story**
_As a teenager that is learning Python for the first time
_I would like to feel confident and excited when looking at the learning resources
_so that I am engaged and keen to learn

**What pages will be changed?**
We will be adding images to the Play and Teach pages on the website, the student dashboard, the resources themselves, and use assets in social media too. We will probably also print some stickers.

**Outcome/deliverable**
Initially, please propose 

- [x] three quick concepts, from these we will need:

Followed by:
- [x] Characters/figures that can be used to 'speak' throughout the resources
- [x] Graphic elements to pick out sections in resources
- [x] Cover graphics for slide and hero image
- [x] Colour palette
- [x] Leading font (for logo and any graphical wording) Body font will remain as _Inter_

**Tools**
Illustrator / Figma

**Concerns**
Ensure all is copyright free 

**Deadline**
As marked by sprints

**Links**
[https://code-for-life.gitbook.io/python-lessons-with-raspberry-pi-ide/3GnBiHhkcxRgUkKhYFz4]

**Reviewer**
@lauracumming 

**People to contact**
@lauracumming 

## Acceptance Criteria
SVGs are saved to folders, artwork is saved to folders, any links and fonts are packaged.

---

### Want to work on this issue?

[Code for Life](https://www.codeforlife.education/) welcomes and encourages community contributions!

If you would like to work on this issue, you can instruct @cfl-bot by commenting one of the following prompts:

|Prompt|Description|Arguments|Use When|
|---|---|---|---|
|*assign me*|Assigns you to this issue.|N/A|You want to work on this issue.|
|*unassign me*|Unassigns you from this issue.|N/A|You no longer want to work on this issue.|
|*ready for review*|Adds the *ready for review* label to this issue.|N/A|You've attached deliverables to this issue and you would like a CFL team member to review it.|
|*requires changes*|Removes the *ready for review* label from this issue.|N/A|You've realized that your deliverables are missing something.|
|*link pr \<number> \<repo?>*|Links a pull request to this issue.|**\<number>** The number of the PR to link.<br/>**\<repo?>** The repo the PR is in.* Defaults to this issue's repo.|You want to associate your code changes with this issue.|
|*unlink pr \<number> \<repo?>*|Unlinks a pull request from this issue.|**\<number>** The number of the PR to unlink.<br/>**\<repo?>** The repo the PR is in.* Defaults to this issue's repo.|You want to disassociate your code changes with this issue.|

*Only [CFL repos](https://github.com/orgs/ocadotechnology/repositories?q=codeforlife-) may be specified. You can optionally omit the "codeforlife-" prefix.

---

[Our Site](https://www.codeforlife.education/) | [Our Docs](https://docs.codeforlife.education/) | [Our Code](https://github.com/ocadotechnology/codeforlife-workspace)
